### ISSUE TITLE
裁剪大图的时候裁剪框能否按比例缩放

### ISSUE THREAD

**Issue by Alwayslazydog** [StevenYuysy/Cropper#1]
我这边的业务场景是处理一些很大的职业照（2000px X 2000PX+），想通过缩放裁剪成半身450*800左手的移动端海报。
然后现在有个问题就是在裁剪层那边图片无法缩放以及裁剪窗口沾满了。
是我的问题但是还不知道哪里有问题。。
`$clip.photoClip({
        width: 450,
        height: 800,
        fileMinSize: 20,
        file: $file,
        defaultImg: "",
        ok: "#clipBtn",
        loadStart: function () {
          console.log("照片读取中");
        },
        loadProgress: function (progress) {
          console.log(progress);
        },
        loadError: function () {
          console.log("图片加载失败");
        },
        loadComplete: function () {
          console.log("照片读取完成");
        },
        imgSizeMin: function (kbs) {
          console.log(kbs, "上传图片过小");
        },
        clipFinish: function (dataURL) {
          document.getElementById("img-view").src = dataURL;
          drawImage(dataURL);
          $popup.modal("close");
        }
      });`
zhjupiter@sina.com

**Comment by StevenYuysy** [comment]
缩放的 API 是提供的，不太确定你那边的问题，能否提供一个复现的链接和相关的代码？

**Comment by Alwayslazydog** [comment]
谢谢啦 已经解决这个问题了
